[project]
name = "callmind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.26.0",
    "langchain-chroma>=0.1.2",
    "mcp>=1.12.0",
    "python-dotenv>=1.1.1",
]
